### ISSUE TITLE
Bilder werden zeitweise nicht geladen

### ISSUE THREAD

**Issue by georgkaser** [eaCe/lazyload#1]
Erstmal danke für dein cooles Addon!

Ich versuche dieses in ein erstes Projekt zu integrieren und habe dabei bemerkt, dass das tatsächliche Bild beim laden der Seite zeitweise nicht geladen wird, wenn sich das Bild vollständig im Viewport befindet und eigentlich nichts nachgeladen werden muss. Es ist nur das verschwommene Bild zu sehen. Caches habe ich mehrmals gelöscht sowohl im Browser als auch den Mediencache.

**Comment by eaCe** [comment]
Hi, danke für das Feedback!

Du hast recht, liegt vermutlich daran das die Bilder noch nicht geladen sind... 
Nutzt man `src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="` scheint das Problem nicht aufzutreten. Ich werde mal schauen ob es einen eleganten Weg gibt das Problem zu umgehen.

**Comment by eaCe** [comment]
Ich habe nun noch ein mal am JS rum geschraubt, vielleicht kannst du das noch ein mal testen.

Weiter kannst du dir die beiden base64 Funktionen auch anschauen:

Die kleinste und schnellste Lösung gibt einen leeren base64-Bild-String zurück:
```php
lazyload::getEmptyBase64();
```
Die zweite Variante gibt das zuvor verkleinerte und verschwommene Bild als base64-String zurück.
```php
lazyload::getBase64('images/lazyimage/bild.jpg');
```
oder:
```php
lazyload::getBase64('index.php?rex_media_type=lazyimage&rex_media_file=bild.jpg');
```
Wenn du eine dieser Varianten als src nutzt sollte es auf keinen Fall Probleme geben.

**Comment by georgkaser** [comment]
Ja, mir scheint jetzt gehts. Ich hab jetzt noch ein weiteres Problem, vielleicht kannst du mir da helfen: Ich stelle Teammitglieder in einem Grid dar. Über ein Suchfeld (http://vdw.github.io/HideSeek/) kann ich diese dann filtern. Beim Filtern gelangen dann Bilder in den Viewport, die noch nicht geladen sind. Wie kann ich die nachladen - gibts da eine Lösung?

**Comment by eaCe** [comment]
Moin, ich habe die bLazy Instanz nun mal global erreichbar gemacht.

Somit könntest du folgendes probieren:

```javascript
$('.hidesseek').hideseek();
$('.hidesseek').on("_after", function() 
{
    window.bLazy.revalidate();
});
```

Es gibt zwar auch die Möglichkeit versteckte Elemente zu laden, nur dann würden vermutlich alle gleichzeitig geladen.

**Comment by georgkaser** [comment]
Genial - es funktioniert! Dicker Daumen nach oben und danke!

**Comment by eaCe** [comment]
Dann mach ich mal zu ;)
