### ISSUE TITLE
Probleme mit Schrift

### ISSUE THREAD

**Issue by erraiva** [eaCe/lazyload#3]
Hallo, beim Aktivieren von "Automatisch CSS und JavaScript einbinden" bekomme ich Probleme mit dem Text auf meiner Website. UTF-8 wird zerstört. Ich denke da ist was doppelt. Sonst ein cooles Tool ;-)

**Comment by eaCe** [comment]
@erraiva hm das ist merkwürdig, ich schau mal ob ich das irgendwie reproduzieren kann
